### ISSUE TITLE
Add love.handlers

### ISSUE THREAD

**Issue by xordspar0** [love2d-community/love-api#57]
There is a table inside `love` called `love.handlers` that doesn't fit into the normal categories. It's not a module, function, or callback. It's just a table where you can define functions to handle user-defined events. It is documented here:
 - https://love2d.org/wiki/love.event
 - https://love2d.org/wiki/love.run

**Comment by MikuAuahDark** [comment]
IIRC the usage of `love.handles` for custom events is not supported. This means it can change between LOVE versions without prior notice or just stop working altogether.

**Comment by pablomayobre** [comment]
These could be added in some way as secret or hidden variables, so that autocomplete providers could "support" them.

Since the love-api is generally deployed in a per-version basis and there are branches for all major releases, if the behaviour were to change, we can change the love-api to match or remove it altogether.

When using this undocumented feature (for example, to write a custom `love.run`, or when writing a library like [`hump.gamestate`](https://github.com/vrld/hump/blob/master/gamestate.lua#L84)) and relying on a tool that uses love-api to check for the existance of the `handlers`, you may end up facing issues like:
- The tool telling you the field doesn't exist
- The tool not knowing it's a table and not allowing you to index it
- The tool telling you that it's a nil value. 

So we could potentially add these to help those tools easily support this field, yet mark them as hidden or readonly or something similar so that people know that they shouldn't be used in normal operation.

I think a similar example to this is `love.run`, it's prone to change between versions, issues with custom `love.run` are the user's problem and yet it's documented for people to play with it, `love.handlers` is no rocket science, I think it deserves some docs at least here...
